// DO NOT EDIT THIS FILE - it is machine generated
#ifndef SPL_JNIFunctions_com_nctu_myutils_h
#define SPL_JNIFunctions_com_nctu_myutils_h

#include <SPL/Runtime/Function/SPLJavaFunction.h>
#include <SPL/Runtime/Type/SPLType.h>

namespace SPL {
namespace JNIFunctions {
namespace com {
namespace nctu {
namespace myutils {
class SPL_JNIFunctions {
public:

// Generated from application.My_java_functionImpl in impl/java/bin/application/My_java_functionImpl$StreamsModel.class at Thu Jul 04 11:53:32 CST 2019
static SPL::int32 add(SPL::int32 const & arg1, SPL::int32 const & arg2) {
    static __thread void *func;
    static __thread jclass classGlobalRef;
    static __thread jmethodID mid;
    if (func == NULL) {
        func = SPL::SPLJavaFunction::loadFunction("16_java_nf_aw", "1.0.0", SPLJAVAFUNCTION_ADL_FILENAME, "impl/java/bin", "application.My_java_functionImpl", "add", "(II)I", "com.nctu.myutils", "public stateful int32 add(int32 a, int32 b)", &classGlobalRef, &mid);
    }
    JNIEnv* env = SPL::SPLJavaFunction::getJNIEnv(func);
    SPL::int32 result = env->CallStaticIntMethod(classGlobalRef, mid, arg1, arg2);
    if (env->ExceptionCheck())
        SPL::SPLJavaFunction::throwCallError(func);
    return result;
}

// Generated from application.My_java_functionImpl in impl/java/bin/application/My_java_functionImpl$StreamsModel.class at Thu Jul 04 11:53:32 CST 2019
static SPL::uint32 add(SPL::uint32 const & arg1, SPL::uint32 const & arg2) {
    SPL::int32 result = add((SPL::int32) arg1, (SPL::int32) arg2);
    return (SPL::uint32) result;
}

// Generated from application.My_java_functionImpl in impl/java/bin/application/My_java_functionImpl$StreamsModel.class at Thu Jul 04 11:53:32 CST 2019
static SPL::rstring getUser() {
    static __thread void *func;
    static __thread jclass classGlobalRef;
    static __thread jmethodID mid;
    if (func == NULL) {
        func = SPL::SPLJavaFunction::loadFunction("16_java_nf_aw", "1.0.0", SPLJAVAFUNCTION_ADL_FILENAME, "impl/java/bin", "application.My_java_functionImpl", "getUser", "()Ljava/lang/String;", "com.nctu.myutils", "public stateful rstring getUser()", &classGlobalRef, &mid);
    }
    JNIEnv* env = SPL::SPLJavaFunction::getJNIEnv(func);
    jstring resObj = (jstring) env->CallStaticObjectMethod(classGlobalRef, mid);
    if (env->ExceptionCheck())
        SPL::SPLJavaFunction::throwCallError(func);
    if (resObj != NULL) {
        const jchar *chars = env->GetStringChars(resObj, NULL);
        if (chars == NULL)
            SPL::SPLJavaFunction::throwCreateError(func);
        SPL::ustring result((const UChar *) chars, (int32_t) env->GetStringLength(resObj));
        env->ReleaseStringChars(resObj, chars);
        env->DeleteLocalRef(resObj);
        return SPL::ustring::toUTF8(result);
    } else {
        return SPL::rstring("");
    }
}

};
}
}
}
}
}
#endif
