/* Generated by Streams Studio: July 4, 2019 at 11:37:57 AM GMT+8 */
package application;


import com.ibm.streams.function.model.Function;

/**
 * Class for implementing SPL Java native function. 
 */

public class My_java_functionImpl  {
	
	static int cumuResult = 0;
	
    @Function(namespace="com.nctu.myutils", name="add", description="add two integers", stateful=true)
    public static int add(int a, int b) {    	
   	    // TODO: Add function implementation
    	
   	    return(a+b);
    }
    
    @Function(namespace="com.nctu.myutils", name="getUser", description="return user ID", stateful=true)
    public static String getUser() {    	
   	    // TODO: Add function implementation
    	
   	    return(System.getenv("USER"));
    }
    
    @Function(namespace="com.nctu.myutilx", name="cumuAdd", description="add two integers and cum result", stateful=true)
    public static int cumuAdd(int a, int b) {    	
   	    // TODO: Add function implementation
    	cumuResult += a+b;
   	    return(cumuResult);
    }
    
}
